-- brand_id, type_id:1 up, 2 grand
INSERT INTO pianos VALUES
            (NULL, 'D-282', 'C. Bechstein Concert',
              ' The C. Bechstein D 282 concert grand piano is a top-class instrument. Thanks to its stupendous and beautiful sound, it’s the ideal grand for large concert halls.
              The C. Bechstein engineers and master piano-makers developed the D 282 model after intensive discussions with international star pianists. This legendary instrument has set new standards with its transparent voice and unparalleled richness of tonal colors. The C. Bechstein D 282 concert grand piano embodies the synthesis of the brand’s legend and the demands of today’s pianists for power and dynamism.
International star pianists confirm the outstanding characteristics of the C. Bechstein D 282 concert grand piano: surprisingly powerful sound, elegant and high-precision action. ',
TRUE, 3, 2,
               'img/CBD282.jpg', 'https://video.com'),
               (NULL, 'Concert 8', 'C. Bechstein Concert 8',
                 'C. Bechstein Concert 8: an unsurpassed professional piano, in keeping with all the C. Bechstein instruments favored since more than 160 years for their unique sound, touch and durability.
The C. Bechstein Concert 8 professional piano is a non plus ultra upright that clearly surpasses many run-of-the-mill grands. Its acoustic assembly, sound volume and colored voice, as well as its precise and highly responsive action, surprise even the most demanding musicians who are used to the touch and sound volume of grand pianos. ',
   TRUE, 3, 1,
                  'img/Concert8.jpg', 'https://video.com'),
                (NULL, 'Grand 290', 'Concert Grand 290 Imperial',
                    'The Italian composer, conductor and pianist Ferruccio Busoni meticulously transcribes the famous organ works of J.S. Bach. He soon realises that he requires additional bass notes in order to do Bach’s masterpieces and the immersive sound of 16 to 32 feet bass pipes found in an organ justice. Ludwig Bösendorfer is ready to take on the challenge and builds the first prototype having full 8 octaves in tonal range. Not only Busoni starts to appreciate the exceptional qualities of the – later coined – Imperial Concert Grand: Bartók, Debussy and Ravel compose further works to exploit the tremendous resonance of this very instrument. These oeuvres can only played and interpreted as they were meant to on this Concert Grand. Evoking an extraordinary sound – sonorous and rich in expression and resonance – the timbre of the Imperial Grand seems to be orchestral. The additional deeper bass notes resonate with every key you strike and the massive soundboard supports the projection of any frequency. Ludwig Bösendorfer’s Imperial still to this day represents the precious heritage of the Bösendorfer piano manufactory. Impressive in sound, imposing in appearance.',
      TRUE, 1, 2,
                     'img/Concert8.jpg', 'https://video.com'),
                (NULL, 'Upright 130', 'Grand Upright 130',
                       'The Bösendorfer 130 is indeed physically an upright piano, yet, surprises with subtle nuances and the powerful bass of a grand piano. We have transferred refined craftsmanship and our sound philosophy in an upright form to this instrument. The precise action offers freedom in articulation and play with maximum controllability. The grand sound of this upright is by no means a surprise since the very Bösendorfer Artisans building our Concert Grands design and craft the Bösendorfer Grand Upright 130, nearly two centuries of sound crafting experience.',
         TRUE, 1, 1,
                        'img/Concert8.jpg', 'https://video.com'),
                (NULL, 'F156', 'Fazioli F156',
                'The smallest model of the FAZIOLI collection. Despite its small size, this piano has a remarkably powerful and clear sound. Suitable for smaller settings where the player does not wish to renounce to the sound and action of a high-quality grand piano.',
                 TRUE, 6, 2,
                'img/Concert8.jpg', 'https://video.com'),
                (NULL, 'F308', 'Fazioli F308',
                'Concert grand. The absolute “jewel in the crown” designed for modern large-capacity concert halls and very big spaces.it has immense power and extraordinary harmonic richness, owing to the increased string length in the bass section. It is endowed with a fourth pedal invented by Fazioli. Located to the left of the three traditional pedals, it reduces the hammer-blow distance THUS reducing the volume without modifying the timbre, at the same time facilitating the performance of glissandos, pianissimos, rapid passages and legatos.',
                TRUE, 6, 2,
                'img/Concert8.jpg', 'https://video.com'),
                (NULL, 'Model D', 'Concert Grand',
                "At 274 cm in length, this majestic musical instrument - the pinnacle of concert grands - is the overwhelming choice of the world's greatest pianists and for anyone who demands the highest level of musical expression.",
                TRUE, 4, 2,
                'img/Concert8.jpg', 'https://video.com'),
                (NULL, 'Model K', 'Traditional K-52',
                "Introduced in 1903, this piano features a larger soundboard than many grands, for a more resonant voice. The choice for professional players seeking an upright instrument — and perfect for all sizes of homes and apartments.",
                TRUE, 4, 1,
                'img/Concert8.jpg', 'https://video.com'),
                (NULL, 'GX-7', 'Kawai GX-7',
                "At the lofty pinnacle of the GX series, the regal GX-7 speaks with the transcendent character and authority that has made it the definitive choice of the consummate professional.",
                TRUE, 2, 2,
                'img/Concert8.jpg', 'https://video.com'),
                (NULL, 'K-700', 'Kawai K-700',
                "The K-700 offers quality tone and expression, boasting Kawai's traditional grand-style exterior design. The unsurpassed value will meet the demand of those who wish for a grand piano but have no space.",
                TRUE, 2, 1,
                'img/Concert8.jpg', 'https://video.com'),
                (NULL, 'GB1K', 'Yamaha GB1K',
                "The GB1K, Yamaha's most compact and affordable grand, is a popular choice for locations where space is somewhat limited, with full resonant tone comparable to that of many substantially larger models.
Unparalleled in their beauty and musical range, grand pianos are the ultimate expression of the piano maker's art. Embodying over 100 years of accumulated expertise, these instruments epitomize the quality, performance and value for which Yamaha has long been renowned, as we enter the second century of Yamaha grand pianos.",
                TRUE, 5, 2,
                'img/Concert8.jpg', 'https://video.com'),
                (NULL, 'U1', 'Yamaha U1',
                "Designed for the experienced pianist and professional musician, Yamaha U1 upright pianos are made in Japan and feature outstanding tone, touch and durability. A perennial favorite among discerning pianists, U1 upright pianos offer outstanding musical performance, setting the standards by which many other upright pianos are measured.",
                TRUE, 5, 1,
                'img/Concert8.jpg', 'https://video.com')
                ;
